---
title: "STATS369 Lab 7"
author: "Bin Kim bkim763 698518689"
date: "10/5/2020"
output: html_document
---


```{r}
library(ranger)
library(janitor)
library(tidyverse)
library(rpart)
load("spam.rda")
wordmatrix_original = wordmatrix
```

# Task 1

```{r}
wordmatrix = as.data.frame(wordmatrix)
spam_frame = cbind(is_spam=df$is_spam, wordmatrix)
spam_frame = janitor::clean_names(spam_frame)

n_trees = c(1:10, seq(20,100,by=10), seq(200,600, by=100))

rf_1 = map(n_trees, function(x) ranger(is_spam ~ ., data=spam_frame, num.trees = x))
rf_2 = map(n_trees, function(x) ranger(is_spam ~ ., data=spam_frame, num.trees = x))
```

# Task 2

```{r}
oob_errors_rf1 = sapply(rf_1, function(x) x$prediction.error)
oob_errors_rf2 = sapply(rf_2, function(x) x$prediction.error)
oob_errors_avg = (oob_errors_rf1 + oob_errors_rf2) / 2
ggplot() + geom_point(aes(n_trees, oob_errors_avg)) + labs(title = "Random Forest: OOB Error Rate vs Number of Trees fitted") + xlab("Number of Trees") + ylab("OOB Error")
```

# Task 3

```{r}
mtries = c(2,5,10,20,30,40,50,200)
rf_3 = map(mtries, function(x) ranger(is_spam ~ ., data=spam_frame, mtry = x))
rf_4 = map(mtries, function(x) ranger(is_spam ~ ., data=spam_frame, mtry = x))
```

# Task 4

```{r}
oob_errors_rf3 = sapply(rf_3, function(x) x$prediction.error)
oob_errors_rf4 = sapply(rf_4, function(x) x$prediction.error)
oob_errors_mtry_avg = (oob_errors_rf3 + oob_errors_rf4) / 2
ggplot() + geom_point(aes(mtries, oob_errors_mtry_avg)) + labs(title = "Random Forest: OOB Error Rate vs mtry") + xlab("mtry") + ylab("OOB Error")
```

The plot shows that the minimum OOB error is achieved when `mtry` is between 20 ~ 30. Default mtry is `sqrt(630) = 25` and that seems to be a very reasonable choice for this case.

# Task 5

Rpart from Assignment 3

```{r}
set.seed(763)
wordmatrix = as.data.frame(wordmatrix)

# cleaning column names
wordmatrix = janitor::clean_names(wordmatrix)
spam_df = cbind(is_spam=df$is_spam, wordmatrix)

# map for colnames(wordmatrix_original) -> colnames(spam_df)
spam_col_map = matrix(NA, nrow = 1, ncol = 630)
colnames(spam_col_map) = colnames(wordmatrix_original)
spam_col_map[1,] = colnames(wordmatrix)

spam_tree = rpart(factor(is_spam) ~ ., data=spam_df)

# rpart confusion matrix
tree_cm = table(actual=spam_df$is_spam, predicted=predict(spam_tree, wordmatrix, type = "class"))
tree_cm
cat("Rpart Accuracy:", sum(tree_cm[c(1,3)]) / sum(tree_cm[c(1,2,3,4)]), "\n")
```

Random forest method was able to achieve up to 1 - 0.02(best OOB error) = 98% accuracy. This is much better than the rpart method.